name: Infra Deploy

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
    - main

env:
  tf_version: 0.15.4
  AWS_ACCESS_KEY_ID: ${{ secrets.WEBSITE_INFRA_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.WEBSITE_INFRA_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-2

jobs:
  terraform_checks:
    name: Terraform checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: tfsec
      uses: tintulip/terraform-security-scan@v2.2.1
      with:
        tfsec_actions_comment: false
    - name: checkov-action
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        quiet: true
        framework: terraform

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

  prod_infra_plan:
    needs: terraform_checks
    runs-on: ubuntu-latest
    env:
      env_name: production
    environment:
      name: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
      with:
        terraform_version: ${{ env.tf_version }}
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -no-color -out=production.tfplan -var-file=env_vars/production.tfvars

    - name: Show Terraform Plan
      run: terraform show -no-color production.tfplan

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.env_name }}.tfplan
        path: ${{ github.workspace }}/${{ env.env_name }}.tfplan

  prod_infra_apply:
    needs: prod_infra_plan
    runs-on: ubuntu-latest
    env:
      env_name: production
    environment:
      name: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Download plan
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.env_name }}.tfplan
        path: ${{ github.workspace }}/
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
      with:
        terraform_version: ${{ env.tf_version }}
    - name: Terraform Init
      run: terraform init
    - name: Terraform Apply
      run: terraform apply -no-color -auto-approve -input=false production.tfplan
