name: Terraform CI

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      AWS_REGION: eu-west-2

    steps:
    - name: Checkout
      users: actions/checkout@v2

    - name: Setup Terraform
      users: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan



 

